### ISSUE TITLE
crash compiling bower css files

### ISSUE THREAD

**Issue by wiltzius** [BlessCSS/bless-brunch#3]
In a brunch config with:

```
    stylesheets:
      joinTo:
        'styles/app.css': [/^client/, /echidna\/shared/]
        'styles/bowerfiles.css': /^bower_components/
```

I hit this crash:

```
  brunch:generate Optimizing '_publish/styles/bowerfiles.css' with 'BlessCompiler' +11s

/Users/wiltzius/Documents/welkin/dugong/node_modules/bless-brunch/lib/index.js:62
        return callback(err, appCssFile.content);
                                       ^
TypeError: Cannot read property 'content' of null
  at /Users/wiltzius/Documents/welkin/dugong/node_modules/bless-brunch/lib/index.js:62:40
  at Object.Parser.parser.parse [as parse] (/Users/wiltzius/Documents/welkin/dugong/node_modules/bless-brunch/node_modules/bless/lib/bless/parser.js:108:13)
  at BlessCompiler.module.exports.BlessCompiler.minify (/Users/wiltzius/Documents/welkin/dugong/node_modules/bless-brunch/lib/index.js:42:19)
  at BlessCompiler.<anonymous> (/Users/wiltzius/Documents/welkin/dugong/node_modules/bless-brunch/lib/index.js:3:59)
  at /Users/wiltzius/Documents/welkin/dugong/node_modules/brunch/lib/fs_utils/generate.js:159:33
  at fn (/Users/wiltzius/Documents/welkin/dugong/node_modules/brunch/node_modules/async-waterfall/index.js:19:24)
  at Object._onImmediate (/Users/wiltzius/Documents/welkin/dugong/node_modules/brunch/node_modules/async-waterfall/index.js:58:22)
  at processImmediate [as _immediateCallback] (timers.js:345:15)
```

Any ideas? Advice appreciated.

**Comment by JLepeltier** [comment]
If you look at the index.js of bless-brunch, 
you will see that you have to rename your css "app.css".

**Comment by thomasconner** [comment]
@wiltzius I just updated the plugin. Please give it a try and see if it resolves your issue.
